---
    AWSTemplateFormatVersion: '2010-09-09'
    Description: 'Setup for EC2 and RDS. This purpose is to enable to connect RDS from local'
    Parameters:
      #ec2_parameter
      #AWS::EC2::Instanceでamiを選択して作成している場合はInstanceのtypeは設定できない
      # InstanceType: 
      #   Type: String
      #   Default: t2.micro
      #   AllowedValues: 
      #     - t2.micro
      #     - t2.nano
      #     - t2.nano
      #   Description: Enter t2.micro, t2.nano, or t2.nano. Default is t2.micro.
      KeyName: 
        Description: Amazon EC2 Key Pair
        Type: "AWS::EC2::KeyPair::KeyName"
      SSHLocation:
        Type: String
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
        Description: " Enter the IP address range that is allowed to connect to EC2"
      #rds_parameter
      RDSInstanceIdentifier:
          Type: String
          Default: database-1
          Description: Enter RDS InstanceIdentifier to identify RDS.
      RDSInstanceType:
          Type: String
          Default: db.r5.large
          AllowedValues:
          - db.r5.large
          - db.r5.xlarge
          - db.r5.2xlarge
          - db.r5.4xlarge
          Description: Enter RDS InstanceType
      RDSDBPort:
          Default: '3306'
          Type: Number
          MinValue: '1150'
          MaxValue: '65535'
          Description: Enter TCP/IP port used to connect DB in RDS.
      RDSDBPwd:
          NoEcho: 'true'
          Type: String
          MinLength: '1'
          MaxLength: '41'
          AllowedPattern: "^[a-zA-Z0-9]*$"
          Description: Enter the database admin account password in RDS
    Resources:
      #ec2
      EC2SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          #vpc_for_ec2_rds.ymlでできたvpc
          VpcId: vpc-xxx
          GroupDescription: Enable SSH access via port 22
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp:
                Ref: SSHLocation
      myEc2Instance: 
        Type: AWS::EC2::Instance
        Properties: 
          #自分が既に持っているec2_ami
          ImageId: ami-xxx
          #ここにはvpcのcfnで作られたpublic subnet idを割り当てる
          SubnetId: subnet-xxx
          KeyName: 
            Ref: KeyName
          #SecurityGroupIds:を設定しなければdefaultのSecurityGroupが割り当てられる
          SecurityGroupIds:
            - Fn::GetAtt: [ EC2SecurityGroup, GroupId ]
          #   #上記はGetattを使うと、そのリソースがまだ作られていなくても、そのリソースの名前を得たりすることができる
          #   #https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
      #rds
      RDSSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: SecurityGroup rds-grp
          #vpc_for_ec2_rds.ymlでできたvpc
          VpcId: vpc-xxx
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort:
                Ref: RDSDBPort
              ToPort:
                Ref: RDSDBPort
              SourceSecurityGroupId:
                Ref: EC2SecurityGroup
      RDSInstance:
        Type: AWS::RDS::DBInstance
        Properties:
          Engine: mysql
          DBInstanceClass:
            Ref: RDSInstanceType
          AllocatedStorage: '20'
          StorageType: gp2
          DBInstanceIdentifier:
            Ref: RDSInstanceIdentifier
          MasterUsername: admin
          MasterUserPassword:
            Ref: RDSDBPwd
          #rdsのサブネットGを設定しないといけないため、そのためだけの構築工数が必要(rdsSubnetG_for_ec2_rds.yml)
          #ここにはそれでできたRDSSubnetGroupの名前を入れる
          DBSubnetGroupName: "xxx"
          PubliclyAccessible: false
          AvailabilityZone: "ap-northeast-1a"
          VPCSecurityGroups:
            - Ref: RDSSecurityGroup
          CopyTagsToSnapshot: true
          BackupRetentionPeriod: 7
          Tags:
            - Key: Application
              Value: string
        DeletionPolicy: Snapshot
