---
    AWSTemplateFormatVersion: '2010-09-09'
    Description: 'Setup for VPC. This purpose is to enable to connect RDS from local'
    Resources:
      #VPC
      myVPC:
        Type: AWS::EC2::VPC
        Properties: 
          CidrBlock: 10.0.0.0/16
          EnableDnsSupport: 'true'
          EnableDnsHostnames: 'true'
          InstanceTenancy: dedicated
          Tags:
          - Key: Name
            Value: myVPC
      #RouteTable
      PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId:  
            Ref: myVPC
          Tags:
          - Key: Name
            Value: PublicRouteTable
      PrivateRouteTable1:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId:  
            Ref: myVPC
          Tags:
          - Key: Name
            Value: PrivateRouteTable1
      PrivateRouteTable2:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId:  
            Ref: myVPC
          Tags:
          - Key: Name
            Value: PrivateRouteTable2
      #Subnet
      PublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId:
            Ref: myVPC
          CidrBlock: 10.0.1.0/24
          AvailabilityZone: "ap-northeast-1a"
          Tags:
          - Key: Name
            Value: PublicSubnet
      PrivateSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId:
            Ref: myVPC
          CidrBlock: 10.0.2.0/24
          AvailabilityZone: "ap-northeast-1a"
          Tags:
          - Key: Name
            Value: PrivateSubnet1
      PrivateSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId:
            Ref: myVPC
          CidrBlock: 10.0.4.0/24
          AvailabilityZone: "ap-northeast-1c"
          Tags:
          - Key: Name
            Value: PrivateSubnet2
      #SubnetRouteTableAssociation(subnetとrouteTableを紐付け、これだけではprivateのまま)
      PublicSubnetRouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties: 
          SubnetId: 
            Ref: PublicSubnet
          RouteTableId: 
            Ref: PublicRouteTable
      PrivateSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties: 
          SubnetId: 
            Ref: PrivateSubnet1
          RouteTableId: 
            Ref: PrivateRouteTable1
      PrivateSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties: 
          SubnetId: 
            Ref: PrivateSubnet2
          RouteTableId: 
            Ref: PrivateRouteTable2
      #InternetGateway
      myInternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties: 
          Tags: 
          - Key: Name
            Value: myInternetGateway
      #AttachGateway(VPCとInternetGatewayの紐付け)
      AttachGateway:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
          VpcId:
            Ref: myVPC
          InternetGatewayId:
            Ref: myInternetGateway
      #AWS:EC2:Route(routeTableとInternetGatewayを紐付け、これをされたrouteTableはpublicになる)
      myRoute:
        Type: AWS::EC2::Route
        DependsOn: myInternetGateway
        Properties:
          RouteTableId:
            Ref: PublicRouteTable
          DestinationCidrBlock: 0.0.0.0/0
          GatewayId:
            Ref: myInternetGateway